// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/kainonly/cronx/api"
	"github.com/kainonly/cronx/api/index"
	"github.com/kainonly/cronx/common"
)

// Injectors from wire.go:

func NewAPI(values *common.Values) (*api.API, error) {
	scheduler, err := UseScheduler()
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:         values,
		Scheduler: scheduler,
	}
	hertz, err := UseHertz(values)
	if err != nil {
		return nil, err
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		V:      values,
		IndexX: service,
	}
	apiAPI := &api.API{
		Inject: inject,
		Hertz:  hertz,
		Index:  controller,
		IndexX: service,
	}
	return apiAPI, nil
}
