// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/kainonly/cronx/api"
	"github.com/kainonly/cronx/api/index"
	"github.com/kainonly/cronx/api/jobs"
	"github.com/kainonly/cronx/api/schedulers"
	"github.com/kainonly/cronx/common"
)

// Injectors from wire.go:

func NewAPI(values *common.Values) (*api.API, error) {
	db, err := UseBadger()
	if err != nil {
		return nil, err
	}
	cronx := UseCronx()
	inject := &common.Inject{
		V:    values,
		Db:   db,
		Cron: cronx,
	}
	hertz, err := UseHertz(values)
	if err != nil {
		return nil, err
	}
	service := &index.Service{
		Inject: inject,
	}
	controller := &index.Controller{
		V:      values,
		IndexX: service,
	}
	jobsService := &jobs.Service{
		Inject: inject,
	}
	jobsController := &jobs.Controller{
		V:     values,
		JobsX: jobsService,
	}
	schedulersService := &schedulers.Service{
		Inject: inject,
	}
	schedulersController := &schedulers.Controller{
		V:           values,
		SchedulersX: schedulersService,
	}
	apiAPI := &api.API{
		Inject:     inject,
		Hertz:      hertz,
		Index:      controller,
		IndexX:     service,
		Jobs:       jobsController,
		Schedulers: schedulersController,
	}
	return apiAPI, nil
}
